server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    password: secret
    username: myuser
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "spring"
              client-secret: "{noop}spring"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                # - "client_credentials"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8082/login/oauth2/code/spring"
              scopes:
                - "openid"
                - "profile"
